// Sample data based on National Consulting India employee structure - MASTER DATABASE

export const sampleAttendanceData = [
  // September 8, 2025 data
  {
    employeeId: 'NCPL025',
    employeeName: 'Mohammed Faisal',
    emailId: 'faisal@nationalconsultingindia.com',
    department: 'Management',
    designation: 'Manager',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '02:06 PM',
    lastOut: '06:32 PM',
    totalHours: '04:26',
    totalHoursDecimal: 4.43,
    earlyEntry: '-',
    lateEntry: '-05:06',
    earlyExit: '-',
    lateExit: '+00:32',
    netHours: '-04:34',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL034',
    employeeName: 'Rakshith R',
    emailId: 'rakshith.r@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '01:53 PM',
    lastOut: '05:59 PM',
    totalHours: '04:06',
    totalHoursDecimal: 4.10,
    earlyEntry: '-',
    lateEntry: '-00:23',
    earlyExit: '-00:01',
    lateExit: '-',
    netHours: '-00:24',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL021',
    employeeName: 'Salman Khan',
    emailId: 'salman.k@nationalconsultingindia.com',
    department: 'Management',
    designation: 'Team Lead',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '11:50 AM',
    lastOut: '08:31 PM',
    totalHours: '08:41',
    totalHoursDecimal: 8.68,
    earlyEntry: '-',
    lateEntry: '-02:50',
    earlyExit: '-',
    lateExit: '+02:31',
    netHours: '-00:19',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL029',
    employeeName: 'Deepanshi Mamgain',
    emailId: 'deepanshi.m@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '11:11 AM',
    lastOut: '07:11 PM',
    totalHours: '08:00',
    totalHoursDecimal: 8.00,
    earlyEntry: '-',
    lateEntry: '-01:11',
    earlyExit: '-',
    lateExit: '+00:11',
    netHours: '-01:00',
    shiftName: '[10:00 AM - 07:00 PM] Dev Team A',
    status: 'Present'
  },
  {
    employeeId: 'NCPL007',
    employeeName: 'Karthik M K',
    emailId: 'karthik.mk@nationalconsultingindia.com',
    department: 'Accounts',
    designation: 'CFO',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '10:52 AM',
    lastOut: '06:44 PM',
    totalHours: '07:52',
    totalHoursDecimal: 7.87,
    earlyEntry: '-',
    lateEntry: '-01:52',
    earlyExit: '-',
    lateExit: '+00:44',
    netHours: '-01:08',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL001',
    employeeName: 'Mohammed Farooq',
    emailId: 'farooq@nationalconsultingindia.com',
    department: 'Management',
    designation: 'EA - Director',
    location: 'Head Office',
    role: 'Admin',
    date: '08-Sep-2025',
    firstIn: '10:28 AM',
    lastOut: '-',
    totalHours: '00:00',
    totalHoursDecimal: 0.00,
    earlyEntry: '-',
    lateEntry: '-00:28',
    earlyExit: '-',
    lateExit: '-',
    netHours: '-',
    shiftName: '[10:00 AM - 07:00 PM] Shift C',
    status: 'Partial'
  },
  {
    employeeId: 'NCPL024',
    employeeName: 'Yahya Ayash Luqman',
    emailId: 'yahya@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Development Manager',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '10:15 AM',
    lastOut: '07:22 PM',
    totalHours: '09:07',
    totalHoursDecimal: 9.12,
    earlyEntry: '-',
    lateEntry: '-00:15',
    earlyExit: '-',
    lateExit: '+00:22',
    netHours: '+00:07',
    shiftName: '[10:00 AM - 07:00 PM] Dev Team A',
    status: 'Present'
  },
  {
    employeeId: 'NCPL032',
    employeeName: 'Sanjay Asthana',
    emailId: 'sanjay.a@nationalconsultingindia.com',
    department: 'Operations',
    designation: 'Operations Executive',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '10:13 AM',
    lastOut: '06:53 PM',
    totalHours: '08:40',
    totalHoursDecimal: 8.67,
    earlyEntry: '-',
    lateEntry: '-01:13',
    earlyExit: '-',
    lateExit: '+00:53',
    netHours: '-00:20',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL002',
    employeeName: 'Shruthi Nandeesh',
    emailId: 'shruthi.d@nationalconsultingindia.com',
    department: 'HR',
    designation: 'Asst Manager HR',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '10:05 AM',
    lastOut: '06:59 PM',
    totalHours: '08:54',
    totalHoursDecimal: 8.90,
    earlyEntry: '-',
    lateEntry: '-01:05',
    earlyExit: '-',
    lateExit: '+00:59',
    netHours: '-00:06',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL033',
    employeeName: 'Neehar Jallu',
    emailId: 'neehar.j@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '10:00 AM',
    lastOut: '07:27 PM',
    totalHours: '09:27',
    totalHoursDecimal: 9.45,
    earlyEntry: '-',
    lateEntry: '-01:00',
    earlyExit: '-',
    lateExit: '+01:27',
    netHours: '+00:27',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL014',
    employeeName: 'Kiran Kumar Uggina',
    emailId: 'kiran.k@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:59 AM',
    lastOut: '07:28 PM',
    totalHours: '09:29',
    totalHoursDecimal: 9.48,
    earlyEntry: '-',
    lateEntry: '-00:59',
    earlyExit: '-',
    lateExit: '+01:28',
    netHours: '+00:29',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL027',
    employeeName: 'Akshay Hondi',
    emailId: 'akshay.h@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:39 AM',
    lastOut: '06:35 PM',
    totalHours: '08:56',
    totalHoursDecimal: 8.93,
    earlyEntry: '-',
    lateEntry: '-00:39',
    earlyExit: '-',
    lateExit: '+00:35',
    netHours: '-00:04',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL037',
    employeeName: 'Ahmed Atique',
    emailId: 'atique.a@nationalconsultingindia.com',
    department: 'Operations',
    designation: 'Operations Manager',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '09:35 AM',
    lastOut: '06:51 PM',
    totalHours: '09:16',
    totalHoursDecimal: 9.27,
    earlyEntry: '-',
    lateEntry: '-00:35',
    earlyExit: '-',
    lateExit: '+00:51',
    netHours: '+00:16',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL009',
    employeeName: 'Nirup Jayanth',
    emailId: 'nirup.j@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:28 AM',
    lastOut: '06:50 PM',
    totalHours: '09:22',
    totalHoursDecimal: 9.37,
    earlyEntry: '-',
    lateEntry: '-00:28',
    earlyExit: '-',
    lateExit: '+00:50',
    netHours: '+00:22',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL016',
    employeeName: 'Shwetha D',
    emailId: 'isuzusupport@nationalconsultingindia.com',
    department: 'Customer Support',
    designation: 'Customer Support Executive',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:27 AM',
    lastOut: '06:27 PM',
    totalHours: '09:00',
    totalHoursDecimal: 9.00,
    earlyEntry: '-',
    lateEntry: '-00:27',
    earlyExit: '-',
    lateExit: '+00:27',
    netHours: '+00:00',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL038',
    employeeName: 'Harshdeep Singh',
    emailId: 'harshdeep.s@nationalconsultingindia.com',
    department: 'Marketing',
    designation: 'Head of Marketing',
    location: 'Head Office',
    role: 'Manager',
    date: '08-Sep-2025',
    firstIn: '09:17 AM',
    lastOut: '06:36 PM',
    totalHours: '09:19',
    totalHoursDecimal: 9.32,
    earlyEntry: '-',
    lateEntry: '-00:17',
    earlyExit: '-',
    lateExit: '+00:36',
    netHours: '+00:19',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL026',
    employeeName: 'Shalini N',
    emailId: 'customerconnect@nationalconsultingindia.com',
    department: 'Customer Support',
    designation: 'Customer Support Executive',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:14 AM',
    lastOut: '06:15 PM',
    totalHours: '09:01',
    totalHoursDecimal: 9.02,
    earlyEntry: '-',
    lateEntry: '-00:14',
    earlyExit: '-',
    lateExit: '+00:15',
    netHours: '+00:01',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL039',
    employeeName: 'Madhan M',
    emailId: 'madhan.m@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '09:01 AM',
    lastOut: '06:03 PM',
    totalHours: '09:02',
    totalHoursDecimal: 9.03,
    earlyEntry: '-',
    lateEntry: '-00:01',
    earlyExit: '-',
    lateExit: '+00:03',
    netHours: '+00:02',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL017',
    employeeName: 'Prasanna Hegde',
    emailId: 'prasanna.h@nationalconsultingindia.com',
    department: 'Sales',
    designation: 'Sales Executive',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '08:58 AM',
    lastOut: '06:48 PM',
    totalHours: '09:50',
    totalHoursDecimal: 9.83,
    earlyEntry: '+00:02',
    lateEntry: '-',
    earlyExit: '-',
    lateExit: '+00:48',
    netHours: '+00:50',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL010',
    employeeName: 'Abhiram C',
    emailId: 'abhiram.c@nationalconsultingindia.com',
    department: 'IT',
    designation: 'IT Support',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '08:57 AM',
    lastOut: '06:01 PM',
    totalHours: '09:04',
    totalHoursDecimal: 9.07,
    earlyEntry: '+00:03',
    lateEntry: '-',
    earlyExit: '-',
    lateExit: '+00:01',
    netHours: '+00:04',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL015',
    employeeName: 'Manjushri G',
    emailId: 'montrasupport@nationalconsultingindia.com',
    department: 'Customer Support',
    designation: 'Customer Support Executive',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '08:44 AM',
    lastOut: '05:49 PM',
    totalHours: '09:05',
    totalHoursDecimal: 9.08,
    earlyEntry: '+00:16',
    lateEntry: '-',
    earlyExit: '-00:11',
    lateExit: '-',
    netHours: '+00:05',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  {
    employeeId: 'NCPL012',
    employeeName: 'Sanjana Jagadeesha',
    emailId: 'sanjana.j@nationalconsultingindia.com',
    department: 'Software Development',
    designation: 'Software Developer',
    location: 'Head Office',
    role: 'Team member',
    date: '08-Sep-2025',
    firstIn: '08:36 AM',
    lastOut: '06:35 PM',
    totalHours: '09:59',
    totalHoursDecimal: 9.98,
    earlyEntry: '+00:24',
    lateEntry: '-',
    earlyExit: '-',
    lateExit: '+00:35',
    netHours: '+00:59',
    shiftName: '[09:00 AM - 06:00 PM] Shift B',
    status: 'Present'
  },
  
  // September 1, 2025 data (keeping some historical data)
  { 
    employeeId: 'NCPL021', 
    employeeName: 'Salman Khan', 
    emailId: 'salman.k@nationalconsultingindia.com', 
    department: 'Management', 
    designation: 'Team Lead', 
    location: 'Head Office', 
    role: 'Manager', 
    date: '01-Sep-2025', 
    firstIn: '11:47 AM', 
    lastOut: '10:34 PM', 
    totalHours: '10:47', 
    totalHoursDecimal: 10.78, 
    earlyEntry: '-', 
    lateEntry: '-02:47', 
    earlyExit: '-', 
    lateExit: '+04:34', 
    netHours: '+01:47', 
    shiftName: '[09:00 AM - 06:00 PM] Shift B', 
    status: 'Present' 
  },
  { 
    employeeId: 'NCPL025', 
    employeeName: 'Mohammed Faisal', 
    emailId: 'faisal@nationalconsultingindia.com', 
    department: 'Management', 
    designation: 'Manager', 
    location: 'Head Office', 
    role: 'Manager', 
    date: '01-Sep-2025', 
    firstIn: '11:29 AM', 
    lastOut: '01:36 PM', 
    totalHours: '02:07', 
    totalHoursDecimal: 2.12, 
    earlyEntry: '-', 
    lateEntry: '-02:29', 
    earlyExit: '-04:24', 
    lateExit: '-', 
    netHours: '-06:53', 
    shiftName: '[09:00 AM - 06:00 PM] Shift B', 
    status: 'Present' 
  },
  { 
    employeeId: 'NCPL029', 
    employeeName: 'Deepanshi Mamgain', 
    emailId: 'deepanshi.m@nationalconsultingindia.com', 
    department: 'Software Development', 
    designation: 'Software Developer', 
    location: 'Head Office', 
    role: 'Team member', 
    date: '01-Sep-2025', 
    firstIn: '11:07 AM', 
    lastOut: '07:09 PM', 
    totalHours: '08:02', 
    totalHoursDecimal: 8.03, 
    earlyEntry: '-', 
    lateEntry: '-01:07', 
    earlyExit: '-', 
    lateExit: '+00:09', 
    netHours: '-00:58', 
    shiftName: '[10:00 AM - 07:00 PM] Dev Team A', 
    status: 'Present' 
  }
];

export const sampleEmployees = [
  // Management Team
  {
    id: "NCPL001",
    name: "Mohammed Farooq",
    department: "Management",
    location: "Head Office",
    position: "EA - Director",
    email: "farooq@nationalconsultingindia.com",
    joiningDate: "2024-01-22",
    status: "Active"
  },
  {
    id: "NCPL021",
    name: "Salman Khan",
    department: "Management",
    location: "Head Office",
    position: "Team Lead",
    email: "salman.k@nationalconsultingindia.com",
    joiningDate: "2024-03-15",
    status: "Active"
  },
  {
    id: "NCPL025",
    name: "Mohammed Faisal",
    department: "Management",
    location: "Head Office",
    position: "Manager",
    email: "faisal@nationalconsultingindia.com",
    joiningDate: "2024-06-10",
    status: "Active"
  },
  
  // HR Department
  {
    id: "NCPL002",
    name: "Shruthi Nandeesh",
    department: "HR",
    location: "Head Office",
    position: "Asst Manager HR",
    email: "shruthi.d@nationalconsultingindia.com",
    joiningDate: "2024-01-22",
    status: "Active"
  },
  
  // Software Development Team
  {
    id: "NCPL024",
    name: "Yahya Ayash Luqman",
    department: "Software Development",
    location: "Head Office",
    position: "Software Development Manager",
    email: "yahya@nationalconsultingindia.com",
    joiningDate: "2024-02-15",
    status: "Active"
  },
  {
    id: "NCPL029",
    name: "Deepanshi Mamgain",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "deepanshi.m@nationalconsultingindia.com",
    joiningDate: "2024-04-07",
    status: "Active"
  },
  {
    id: "NCPL028",
    name: "Adityaa Nagarajan",
    department: "Software Development",
    location: "Head Office",
    position: "Full Stack Developer",
    email: "aadityaa@nationalconsultingindia.com",
    joiningDate: "2024-05-20",
    status: "Active"
  },
  {
    id: "NCPL018",
    name: "Siddharth Venkat",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "siddharth.v@nationalconsultingindia.com",
    joiningDate: "2024-07-12",
    status: "Active"
  },
  {
    id: "NCPL033",
    name: "Neehar Jallu",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "neehar.j@nationalconsultingindia.com",
    joiningDate: "2024-08-01",
    status: "Active"
  },
  {
    id: "NCPL014",
    name: "Kiran Kumar Uggina",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "kiran.k@nationalconsultingindia.com",
    joiningDate: "2024-06-15",
    status: "Active"
  },
  {
    id: "NCPL027",
    name: "Akshay Hondi",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "akshay.h@nationalconsultingindia.com",
    joiningDate: "2024-09-01",
    status: "Active"
  },
  {
    id: "NCPL039",
    name: "Madhan M",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "madhan.m@nationalconsultingindia.com",
    joiningDate: "2024-05-10",
    status: "Active"
  },
  {
    id: "NCPL034",
    name: "Rakshith R",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "rakshith.r@nationalconsultingindia.com",
    joiningDate: "2024-07-25",
    status: "Active"
  },
  
  // IT Department
  {
    id: "NCPL019",
    name: "Balasubramanian Pillai",
    department: "IT",
    location: "Head Office",
    position: "Manager IT",
    email: "bala@nationalconsultingindia.com",
    joiningDate: "2025-03-03",
    status: "Active"
  },
  
  // Accounts/Finance
  {
    id: "NCPL007",
    name: "Karthik M K",
    department: "Accounts",
    location: "Head Office",
    position: "CFO",
    email: "karthik.mk@nationalconsultingindia.com",
    joiningDate: "2024-01-15",
    status: "Active"
  },
  {
    id: "NCPL017",
    name: "Prasanna Hegde",
    department: "Sales",
    location: "Head Office",
    position: "Sales Executive",
    email: "prasanna.h@nationalconsultingindia.com",
    joiningDate: "2025-02-10",
    status: "Active"
  },
  
  // Marketing Department
  {
    id: "NCPL038",
    name: "Harshdeep Singh",
    department: "Marketing",
    location: "Head Office",
    position: "Head of Marketing",
    email: "harshdeep.s@nationalconsultingindia.com",
    joiningDate: "2024-03-20",
    status: "Active"
  },
  
  // Operations
  {
    id: "NCPL037",
    name: "Ahmed Atique",
    department: "Operations",
    location: "Head Office",
    position: "Operations Manager",
    email: "atique.a@nationalconsultingindia.com",
    joiningDate: "2024-04-12",
    status: "Active"
  },
  
  // Customer Support
  {
    id: "NCPL026",
    name: "Shalini N",
    department: "Customer Support",
    location: "Head Office",
    position: "Customer Support Executive",
    email: "customerconnect@nationalconsultingindia.com",
    joiningDate: "2024-06-01",
    status: "Active"
  },
  {
    id: "NCPL016",
    name: "Shwetha D",
    department: "Customer Support",
    location: "Head Office",
    position: "Customer Support Executive",
    email: "isuzusupport@nationalconsultingindia.com",
    joiningDate: "2024-05-15",
    status: "Active"
  },
  {
    id: "NCPL015",
    name: "Manjushri G",
    department: "Customer Support",
    location: "Head Office",
    position: "Customer Support Executive",
    email: "montrasupport@nationalconsultingindia.com",
    joiningDate: "2024-07-01",
    status: "Active"
  },
  
  // Security
  {
    id: "NCPL003",
    name: "Sheik Munavar",
    department: "Security",
    location: "Head Office",
    position: "Security Officer",
    email: "munavar@nationalconsultingindia.com",
    joiningDate: "2024-02-01",
    status: "Active"
  },
  
  // Administration
  {
    id: "NCPL023",
    name: "Mamatha M",
    department: "Administration",
    location: "Head Office",
    position: "Administrative Assistant",
    email: "mamatha.m@nationalconsultingindia.com",
    joiningDate: "2024-03-01",
    status: "Active"
  },
  
  // Additional employees from attendance data
  {
    id: "NCPL012",
    name: "Sanjana Jagadeesha",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "sanjana.j@nationalconsultingindia.com",
    joiningDate: "2024-08-15",
    status: "Active"
  },
  {
    id: "NCPL032",
    name: "Sanjay Asthana",
    department: "Operations",
    location: "Head Office",
    position: "Operations Executive",
    email: "sanjay.a@nationalconsultingindia.com",
    joiningDate: "2024-06-20",
    status: "Active"
  },
  {
    id: "NCPL009",
    name: "Nirup Jayanth",
    department: "Software Development",
    location: "Head Office",
    position: "Software Developer",
    email: "nirup.j@nationalconsultingindia.com",
    joiningDate: "2024-04-25",
    status: "Active"
  }
];

export const sampleAttendance = [
  {
    employeeId: "NCPL021",
    date: "2025-09-08",
    checkIn: "11:47",
    checkOut: "22:34",
    status: "Present",
    workingHours: "10h 47m"
  },
  {
    employeeId: "NCPL001",
    date: "2025-09-08",
    checkIn: "10:16",
    checkOut: "21:01",
    status: "Present",
    workingHours: "10h 45m"
  },
  {
    employeeId: "NCPL024",
    date: "2025-09-08",
    checkIn: "10:37",
    checkOut: "19:30",
    status: "Present",
    workingHours: "8h 53m"
  },
  {
    employeeId: "NCPL002",
    date: "2025-09-08",
    checkIn: "10:22",
    checkOut: "19:05",
    status: "Present",
    workingHours: "8h 43m"
  },
  {
    employeeId: "NCPL028",
    date: "2025-09-08",
    checkIn: "09:56",
    checkOut: "19:14",
    status: "Present",
    workingHours: "9h 18m"
  },
  {
    employeeId: "NCPL038",
    date: "2025-09-08",
    checkIn: "09:43",
    checkOut: "18:43",
    status: "Present",
    workingHours: "9h 00m"
  },
  {
    employeeId: "NCPL019",
    date: "2025-09-08",
    checkIn: "08:51",
    checkOut: "20:34",
    status: "Present",
    workingHours: "11h 43m"
  }
];

export const sampleLeaveRecords = [
  {
    id: "LV-2218",
    employeeId: "NCPL024",
    leaveType: "Casual Leave",
    fromDate: "2025-09-07",
    toDate: "2025-09-07",
    days: 1,
    reason: "Personal work",
    status: "Approved",
    appliedDate: "2025-09-05"
  },
  {
    id: "LV-2219",
    employeeId: "NCPL001",
    leaveType: "Sick Leave",
    fromDate: "2025-09-10",
    toDate: "2025-09-11",
    days: 2,
    reason: "Medical checkup",
    status: "Pending",
    appliedDate: "2025-09-06"
  }
];

export const sampleOrganization = {
  name: "National Consulting India",
  totalEmployees: 35,
  departments: [
    { name: "IT", count: 9 },
    { name: "Management", count: 6 },
    { name: "Accounts", count: 4 },
    { name: "Software Development", count: 3 },
    { name: "HR", count: 2 },
    { name: "Marketing", count: 7 },
    { name: "Legal", count: 1 },
    { name: "Real estate", count: 2 },
    { name: "Business Development", count: 2 },
    { name: "iSky", count: 1 },
    { name: "Admin", count: 1 }
  ],
  locations: [
    { name: "Head Office", count: 35 }
  ]
};

export const sampleTimeTracker = [
  {
    employeeId: "NCPL019",
    date: "2025-09-07",
    projectName: "Dashboard Development",
    hoursWorked: 8.5,
    description: "Working on Zoho People dashboard UI"
  },
  {
    employeeId: "NCPL017",
    date: "2025-09-07",
    projectName: "Financial Analysis",
    hoursWorked: 8.0,
    description: "Monthly financial report preparation"
  }
];

export const sampleDashboardData = {
  kpis: {
    totalEmployees: 35,
    presentToday: 32,
    pendingApprovals: 3,
    avgCheckin: "10:15"
  },
  charts: {
    trendData: [
      { day: "Mon", checkins: 32, checkouts: 30 },
      { day: "Tue", checkins: 34, checkouts: 33 },
      { day: "Wed", checkins: 35, checkouts: 34 },
      { day: "Thu", checkins: 31, checkouts: 29 },
      { day: "Fri", checkins: 33, checkouts: 32 },
      { day: "Sat", checkins: 8, checkouts: 7 },
      { day: "Sun", checkins: 3, checkouts: 2 },
    ],
    attendanceSplit: [
      { name: "Present", value: 28, color: "#0ea5e9" },
      { name: "WFH", value: 4, color: "#22c55e" },
      { name: "Leave", value: 2, color: "#f59e0b" },
      { name: "OD", value: 1, color: "#6366f1" },
      { name: "Absent", value: 0, color: "#ef4444" },
    ],
    regularizationData: [
      { date: "Sep 01", count: 2 },
      { date: "Sep 02", count: 1 },
      { date: "Sep 03", count: 3 },
      { date: "Sep 04", count: 2 },
      { date: "Sep 05", count: 1 },
      { date: "Sep 06", count: 2 },
      { date: "Sep 07", count: 1 },
    ]
  },
  tables: {
    todayAttendance: [
      { name: "Salman Khan", dept: "Management", location: "Head Office", status: "Present", time: "11:47 - 22:34", hours: "10h 47m" },
      { name: "Mohammed Farooq", dept: "Management", location: "Head Office", status: "Present", time: "10:16 - 21:01", hours: "10h 45m" },
      { name: "Yahya Ayash Luqman", dept: "Software Development", location: "Head Office", status: "Present", time: "10:37 - 19:30", hours: "8h 53m" },
      { name: "Shruthi Nandeesh", dept: "HR", location: "Head Office", status: "Present", time: "10:22 - 19:05", hours: "8h 43m" },
      { name: "Adityaa Nagarajan", dept: "Software Development", location: "Head Office", status: "Present", time: "09:56 - 19:14", hours: "9h 18m" },
      { name: "Harshdeep Singh", dept: "Marketing", location: "Head Office", status: "Present", time: "09:43 - 18:43", hours: "9h 00m" },
      { name: "Balasubramanian Pillai", dept: "IT", location: "Head Office", status: "Present", time: "08:51 - 20:34", hours: "11h 43m" },
      { name: "Deepanshi Mamgain", dept: "Software Development", location: "Head Office", status: "Present", time: "11:10 - 19:32", hours: "8h 22m" },
    ],
    pendingApprovals: [
      { id: "RG-1042", type: "Regularization", by: "Prasanna H", for: "Sep 06 • 09:20", age: "1d" },
      { id: "LV-2218", type: "Leave", by: "Ashwin K", for: "Sep 09-10 • Casual", age: "2d" },
      { id: "WF-0081", type: "WFH", by: "Mohammed F", for: "Sep 08 • Full Day", age: "1d" },
    ]
  }
};
